version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: betting_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: betting_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run build && npm start"

  frontend:
    build: ./frontend
    container_name: betting_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
